VIA_ENABLE = yes

TAP_DANCE_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
PMW33XX_LIFTOFF_DISTANCE = 0x02 # default = 0x02
# ROTATIONAL_TRANSFORM_ANGLE = 0 # default = 0, -30, -90
# POINTING_DEVICE_INVERT_X = yes
# POINTING_DEVICE_INVERT_Y = yes

MOUSEKEY_ENABLE = yes

KEY_LOCK_ENABLE = yes

# CONSOLE_ENABLE = yes
